package detektrunner

import (
	"fmt"
	"os"
	"path/filepath"
)

const initScriptName = "kdoctor-detekt.init.gradle.kts"

// Plantilla equivalente al bloque Kotlin inline mostrado en Tarea 1.4.
// Se escribe a projectDir y ./gradlew lo carga con --init-script.
//
// Nota multi-módulo: rootProject.layout.buildDirectory resuelve a
// <ProjectDir>/build/ en single-module, pero en multi-module el init-script
// debe ejecutarse por-subprojecto. Por simplicidad Fase 1 fuerza
// allprojects { detekt { ... } } y runGradlew se encarga con find recursivo.
var initScriptTemplate = `// Generated by kdoctor — do not edit by hand.
// Configures Detekt to emit only SARIF (xml = false) into build/reports/detekt/.
// Phase 1 PoC: rollback/migration is not customized.
allprojects {
	detekt {
		xml = false
		sarif {
			required = true
			output = rootProject.layout.buildDirectory
				.file("reports/detekt/kdoctor.sarif").get().asFile
		}
	}
}
`

// WriteInitScript escribe el init-script en projectDir y devuelve la ruta
// absoluta del archivo creado.
func WriteInitScript(projectDir string) (string, error) {
	if projectDir == "" {
		return "", fmt.Errorf("projectDir required")
	}
	path := filepath.Join(projectDir, initScriptName)
	if err := os.WriteFile(path, []byte(initScriptTemplate), 0644); err != nil {
		return "", fmt.Errorf("write init-script: %w", err)
	}
	return path, nil
}
