// Package markdown renders a kdoctor Report as a legible Markdown file.
//
// It is consumed by `kdoctor scan --md` and produces kdoctor-report.md
// with an summary, cluster breakdown, top clusters and actionable findings.
package markdown

import (
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/adkd/adkd/internal/core/types"
)

// Write renders the full report as Markdown to w.
func Write(r types.Report, w io.Writer) error {
	_, err := fmt.Fprint(w, render(r, false))
	return err
}

// WriteSummary renders only the executive summary and top clusters.
func WriteSummary(r types.Report, w io.Writer) error {
	_, err := fmt.Fprint(w, render(r, true))
	return err
}

// render builds the markdown string. If summaryOnly is true, only the header,
// summary, and top clusters are rendered.
func render(r types.Report, summaryOnly bool) string {
	var b strings.Builder

	writeHeader(&b, r)
	writeSummary(&b, r)
	writeTopClusters(&b, r)
	if !summaryOnly {
		writeFindings(&b, r)
	}
	writeFooter(&b)

	return b.String()
}

func writeHeader(b *strings.Builder, r types.Report) {
	b.WriteString("# KDoctor Report\n\n")
	b.WriteString(fmt.Sprintf("- **Health Score:** %d/100\n", r.HealthScore))
	b.WriteString(fmt.Sprintf("- **Project Type:** %s\n", r.ProjectType))
	b.WriteString(fmt.Sprintf("- **Schema Version:** %s\n", r.SchemaVersion))
	b.WriteString("\n")
}

func writeSummary(b *strings.Builder, r types.Report) {
	b.WriteString("## Summary\n\n")
	b.WriteString(fmt.Sprintf("| Errors | Warnings | Info | Total |\n"))
	b.WriteString(fmt.Sprintf("|--------|----------|------|-------|\n"))
	b.WriteString(fmt.Sprintf("| %d | %d | %d | %d |\n\n",
		r.Summary.Errors, r.Summary.Warnings, r.Summary.Info, r.Summary.Total))
}

func writeTopClusters(b *strings.Builder, r types.Report) {
	clusters := groupByCluster(r.Findings)
	if len(clusters) == 0 {
		return
	}

	sorted := sortClustersByCount(clusters)

	b.WriteString("## Top Clusters\n\n")
	b.WriteString("| Cluster | Issues | Severity Breakdown |\n")
	b.WriteString("|---------|--------|-------------------|\n")

	for i, cl := range sorted {
		if i >= 5 {
			break
		}
		sevBreakdown := severityBreakdown(clusters[cl])
		b.WriteString(fmt.Sprintf("| %s | %d | %s |\n", cl, len(clusters[cl]), sevBreakdown))
	}
	b.WriteString("\n")
}

func writeFindings(b *strings.Builder, r types.Report) {
	b.WriteString("## Findings\n\n")

	clusters := groupByCluster(r.Findings)
	if len(clusters) == 0 {
		b.WriteString("_No issues found._\n\n")
		return
	}

	sorted := sortClusters(clusters)
	for _, cl := range sorted {
		b.WriteString(fmt.Sprintf("### %s\n\n", cl))
		b.WriteString("| Rule | Severity | File | Line | Message | Fix Hint |\n")
		b.WriteString("|------|----------|------|------|---------|----------|\n")
		for _, f := range clusters[cl] {
			fix := f.FixHint
			if fix == "" {
				fix = "-"
			}
			b.WriteString(fmt.Sprintf("| `%s` | %s | `%s` | %d | %s | %s |\n",
				f.ID, f.Severity, escapeMD(f.File), f.Line, escapeMD(f.Message), escapeMD(fix)))
		}
		b.WriteString("\n")
	}
}

func writeFooter(b *strings.Builder) {
	b.WriteString("---\n\n")
	b.WriteString("Generated by [kdoctor](https://github.com/adkd/adkd).\n")
}

func groupByCluster(findings []types.Finding) map[string][]types.Finding {
	clusters := map[string][]types.Finding{}
	for _, f := range findings {
		clusters[f.Cluster] = append(clusters[f.Cluster], f)
	}
	return clusters
}

func sortClusters(clusters map[string][]types.Finding) []string {
	keys := make([]string, 0, len(clusters))
	for k := range clusters {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func sortClustersByCount(clusters map[string][]types.Finding) []string {
	keys := make([]string, 0, len(clusters))
	for k := range clusters {
		keys = append(keys, k)
	}
	sort.SliceStable(keys, func(i, j int) bool {
		return len(clusters[keys[i]]) > len(clusters[keys[j]])
	})
	return keys
}

func escapeMD(s string) string {
	// Escapa caracteres que rompen tablas markdown y normaliza saltos de línea.
	s = strings.ReplaceAll(s, "\r\n", " ")
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.ReplaceAll(s, "`", "\\`")
	s = strings.ReplaceAll(s, "*", "\\*")
	s = strings.ReplaceAll(s, "_", "\\_")
	s = strings.ReplaceAll(s, "~", "\\~")
	return s
}

func severityBreakdown(findings []types.Finding) string {
	errors := 0
	warnings := 0
	info := 0
	for _, f := range findings {
		switch f.Severity {
		case types.SeverityError:
			errors++
		case types.SeverityWarning:
			warnings++
		case types.SeverityInfo:
			info++
		}
	}
	return fmt.Sprintf("%d errors, %d warnings, %d info", errors, warnings, info)
}
